### Custom Emojis ###

[[emoji]]
match = "Lab"
emoji = "ğŸ«"

[[emoji]]
match = "CJZ"
emoji = "ğŸ "

[[emoji]]
match = "CYY"
emoji = "ğŸ "

[[emoji]]
match = "ZZH"
emoji = "ğŸ "

### Countries & Regions ###

[[emoji]]
match = "Argentina|é˜¿æ ¹å»·"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "Australia|æ¾³å¤§åˆ©äºš"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "Austria|å¥¥åœ°åˆ©"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "Brazil|å·´è¥¿"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "Bulgaria|ä¿åŠ åˆ©äºš"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "Canada|åŠ æ‹¿å¤§"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "Chile|æ™ºåˆ©"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "China|ä¸­å›½"
emoji = "ğŸ‡¨ğŸ‡³"

[[emoji]]
match = "France|æ³•å›½"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "Germany|å¾·å›½"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "Hong Kong|é¦™æ¸¯"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "Hungary|åŒˆç‰™åˆ©"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "Ireland|çˆ±å°”å…°"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "India|å°åº¦"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "Indonesia|å°åº¦å°¼è¥¿äºš"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "Japan|æ—¥æœ¬"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "Korea|éŸ©å›½"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "Malaysia|é©¬æ¥è¥¿äºš"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "Netherlands|è·å…°"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "Pakistan|å·´åŸºæ–¯å¦"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "Philippines|è²å¾‹å®¾"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "Russia|ä¿„ç½—æ–¯"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "Singapore|æ–°åŠ å¡"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "Sweden|ç‘å…¸"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "Switzerland|ç‘å£«"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "Taiwan|å°æ¹¾"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "Thailand|æ³°å›½"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "Turkey|åœŸè€³å…¶"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "United Kingdom|è‹±å›½"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "United States|ç¾å›½"
emoji = "ğŸ‡ºğŸ‡¸"
