### Custom Emojis ###

[[emoji]]
match = "Lab"
emoji = "ğŸ«"

[[emoji]]
match = "CJZ"
emoji = "ğŸ "

[[emoji]]
match = "CYY"
emoji = "ğŸ "

### Countries & Regions ###

[[emoji]]
match = "Argentina|AR|é˜¿æ ¹å»·"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "Australia|AU|æ¾³å¤§åˆ©äºš"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "Austria|AT|å¥¥åœ°åˆ©"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "Brazil|BR|å·´è¥¿"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "Bulgaria|BG|ä¿åŠ åˆ©äºš"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "Canada|CA|åŠ æ‹¿å¤§"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "Chile|CL|æ™ºåˆ©"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "China|CN|ä¸­å›½"
emoji = "ğŸ‡¨ğŸ‡³"

[[emoji]]
match = "France|FR|æ³•å›½"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "Germany|DE|å¾·å›½"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "Hong Kong|HK|é¦™æ¸¯"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "Hungary|HU|åŒˆç‰™åˆ©"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "Ireland|IE|çˆ±å°”å…°"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "India|IN|å°åº¦"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "Indonesia|ID|å°åº¦å°¼è¥¿äºš"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "Japan|JP|æ—¥æœ¬"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "Korea|KR|éŸ©å›½"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "Malaysia|MY|é©¬æ¥è¥¿äºš"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "Netherlands|NL|è·å…°"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "Pakistan|PK|å·´åŸºæ–¯å¦"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "Philippines|PH|è²å¾‹å®¾"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "Russia|RU|ä¿„ç½—æ–¯"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "Singapore|SG|æ–°åŠ å¡"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "Sweden|SE|ç‘å…¸"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "Switzerland|CH|ç‘å£«"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "Taiwan|TW|å°æ¹¾"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "Thailand|TH|æ³°å›½"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "Turkey|TR|åœŸè€³å…¶"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "United Kingdom|UK|è‹±å›½"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "United States|US|ç¾å›½"
emoji = "ğŸ‡ºğŸ‡¸"
