### DIRECT ###

# AliDNS DoH
[[rulesets]]
group = "DIRECT"
ruleset = "[]DOMAIN,dns.alidns.com"

# DNSPod DoH
[[rulesets]]
group = "DIRECT"
ruleset = "[]DOMAIN-SUFFIX,doh.pub"

# subconverter
[[rulesets]]
group = "DIRECT"
ruleset = "[]DOMAIN,subconverter.imbytecat.com"

### Blocking ###

# bilibili PCDN
[[rulesets]]
group = "REJECT"
ruleset = "[]DOMAIN-SUFFIX,mcdn.bilivideo.cn"

[[rulesets]]
group = "REJECT"
ruleset = "[]DOMAIN-SUFFIX,szbdyd.com"

### Intranet Resources ###

# Home Intranet
[[rulesets]]
group = "ğŸ  CJZ"
ruleset = "[]IP-CIDR,10.0.0.0/23"

# Home Intranet
[[rulesets]]
group = "ğŸ  DXP"
ruleset = "[]IP-CIDR,10.225.0.0/16"

# # CYY Intranet
# [[rulesets]]
# group = "ğŸ  CYY"
# ruleset = "[]IP-CIDR,10.5.0.0/16"

# [[rulesets]]
# group = "ğŸ  CYY"
# ruleset = "[]IP-CIDR,10.6.0.0/16"

# [[rulesets]]
# group = "ğŸ  CYY"
# ruleset = "[]DOMAIN-SUFFIX,cyy.ipddns.cn"

# Putuo Intranet
[[rulesets]]
group = "ğŸ  Putuo"
ruleset = "[]IP-CIDR,10.24.0.0/16"

# Dod3 Intranet
[[rulesets]]
group = "ğŸ  Dod3"
ruleset = "[]IP-CIDR,11.0.0.0/8"

### Special ###

# WeChat
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml"
type = "clash-classic"

# Common Game Delivery CDN
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.yaml"
type = "clash-classic"

# Steam (CN) Game Delivery CDN
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml"
type = "clash-classic"

# Xbox Game Delivery CDN
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Xbox/download-cdn.yaml"
type = "clash-classic"

# Xbox (CN) Game Delivery CDN
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Xbox/download-cdn-cn.yaml"
type = "clash-classic"

# Telegram
[[rulesets]]
group = "Default Proxy"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

# Linkedin
# Redirect to China version for visitors from China
[[rulesets]]
group = "Default Proxy"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LinkedIn/LinkedIn.yaml"
type = "clash-classic"

# å°ä¼—è½¯ä»¶
# No comment area for visitors from China
[[rulesets]]
group = "Default Proxy"
ruleset = "[]DOMAIN-SUFFIX,appinn.com"

# PikPak
[[rulesets]]
group = "Default Proxy"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml"
type = "clash-classic"

### Speedtest Services ###

[[rulesets]]
group = "ğŸš€ Speedtest"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml"
type = "clash-classic"

### Finance ###

# PayPal
[[rulesets]]
group = "ğŸ’° PayPal"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
type = "clash-classic"

# Stripe
[[rulesets]]
group = "ğŸ’³ Stripe"
ruleset = "[]DOMAIN-SUFFIX,stripe.com"

### Technology ###

# OpenAI
[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/OpenAI/openai.yaml"
type = "clash-classic"

# Bing
[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "[]DOMAIN-SUFFIX,bing.com"

[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "[]DOMAIN-SUFFIX,bingapis.com"

# Claude
[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "[]DOMAIN-SUFFIX,claude.ai"

[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "[]DOMAIN-SUFFIX,anthropic.com"

[[rulesets]]
group = "ğŸ¤–ï¸ AI"
ruleset = "[]DOMAIN-SUFFIX,perplexity.ai"

### Cryptocurrency ###

# Kraken
[[rulesets]]
group = "ğŸ“ˆ Crypto"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Kraken/kraken.yaml"
type = "clash-classic"

# Binance
[[rulesets]]
group = "ğŸ“ˆ Crypto"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Binance/binance.yaml"
type = "clash-classic"

# Nexo
[[rulesets]]
group = "ğŸ“ˆ Crypto"
ruleset = "[]DOMAIN-SUFFIX,nexo.com"

# Others
[[rulesets]]
group = "ğŸ“ˆ Crypto"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Crypto/Crypto.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ“ˆ Crypto"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cryptocurrency/Cryptocurrency.yaml"
type = "clash-classic"

### Streaming Media ###
[[rulesets]]
group = "ğŸ¬ Streaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml"
type = "clash-classic"

### Gaming Services ###

# Steam
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml"
type = "clash-classic"

# Nintendo
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml"
type = "clash-classic"

# EA
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.yaml"
type = "clash-classic"

# Origin
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.yaml"
type = "clash-classic"

# Xbox
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.yaml"
type = "clash-classic"

# Epic Games
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml"
type = "clash-classic"

# Blizzard
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.yaml"
type = "clash-classic"

# Discord
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml"
type = "clash-classic"

# COD
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "[]DOMAIN-SUFFIX,activision.com"
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "[]DOMAIN-SUFFIX,callofduty.com"
[[rulesets]]
group = "ğŸ® Gaming"
ruleset = "[]DOMAIN-SUFFIX,demonware.net"

### AS Services ###

# Duolingo
# Recommended to use Singapore IP for users in China
[[rulesets]]
group = "AS Services"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Duolingo/duolingo.yaml"
type = "clash-classic"

# LINE
[[rulesets]]
group = "AS Services"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml"
type = "clash-classic"

# LINE TV
[[rulesets]]
group = "AS Services"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.yaml"
type = "clash-classic"

### EU Services ###

# N26
[[rulesets]]
group = "EU Services"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/N26/n26.yaml"
type = "clash-classic"

# Curve
[[rulesets]]
group = "EU Services"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/Curve/curve.yaml"
type = "clash-classic"

# Wise
[[rulesets]]
group = "EU Services"
ruleset = "[]DOMAIN-SUFFIX,wise.com"

### NA Services ###

# Ultra Mobile
[[rulesets]]
group = "NA Services"
ruleset = "https://raw.githubusercontent.com/imbytecat/clash-rules/main/Rules/UltraMobile/ultra-mobile.yaml"
type = "clash-classic"

### DIRECT ###

# China
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml"
type = "clash-classic"

# GeoIP: CN
[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

### Others ###

# Google
[[rulesets]]
group = "ğŸ” Google"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
type = "clash-classic"

# Global
[[rulesets]]
group = "Default Proxy"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml"
type = "clash-classic"

# LAN IP CIDR
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
type = "clash-ipcidr"

# Final (Others)
[[rulesets]]
group = "Others"
ruleset = "[]MATCH"
